name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:

  # --------------------------------------------------
  # LINT JOB
  # --------------------------------------------------
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # --------------------------------------------------
  # UNIT TEST JOB
  # --------------------------------------------------
  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  # --------------------------------------------------
  # INSTRUMENTATION TEST JOB (ESPRESSO)
  # --------------------------------------------------
  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest      # macOS recommended for stable emulator

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run espresso tests
      # Use lightweight API-level 29 emulator
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default           # FAST, stable
          arch: x86
          profile: Pixel_5          # small & fast
          ram-size: 2048M
          disk-size: 6000M
          disable-animations: true
          emulator-options: >
            -no-window
            -no-snapshot
            -noaudio
            -no-boot-anim
            -gpu swiftshader_indirect
          script: ./gradlew connectedDebugAndroidTest
          timeout-minutes: 25       # prevent boot timeout

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
