name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:

  # --------------------------------------------------
  # LINT JOB
  # --------------------------------------------------
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # --------------------------------------------------
  # UNIT TEST JOB
  # --------------------------------------------------
  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  # --------------------------------------------------
  # INSTRUMENTATION TEST JOB (ESPRESSO)
  # --------------------------------------------------
  instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install emulator dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils libgl1-mesa-dev

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 40
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a        # << ðŸ”¥ THE FIX >>
          force-avd-creation: true
          disable-animations: true
          disable-emu-snapshot: true
          emulator-options: >
            -no-window
            -noaudio
            -no-snapshot
            -no-boot-anim
            -gpu swiftshader_indirect
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
